table customer_with_gender_city
	lineageTag: d176ac4d-1ced-4176-87eb-e6e21211ab35

	column customer_id
		dataType: string
		lineageTag: f829c24c-63cd-46b7-ba0f-94676bc7ae6e
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column signup_date
		dataType: string
		lineageTag: a1008ca6-3717-4b49-84b6-71ba68fc7e93
		summarizeBy: none
		sourceColumn: signup_date

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: fd45c2ff-8d53-4a1e-a114-3b2ef670b8ef
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: e97f41e7-1f60-4523-a632-46b8d8d0ef03
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 78581d6d-623d-441b-aef7-23362069d5b8
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: e96435c0-5f0e-4efa-b273-3f8851b89843
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column customer_type
		dataType: string
		lineageTag: 246714c1-9490-4ad2-8bbf-3e5f334175e1
		summarizeBy: none
		sourceColumn: customer_type

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 09aff39a-45eb-47a6-a518-b28f769d610c
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	partition customer_with_gender_city = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\THAOVY\Downloads\SWE40006\customer_with_gender_city.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"signup_date", type text}, {"full_name", type text}, {"email", type text}, {"phone", type text}, {"city", type text}, {"customer_type", type text}, {"gender", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

