table orders
	lineageTag: 0dddfac8-52df-4bfd-8cb5-03b4a7cce57a

	column order_id
		dataType: string
		lineageTag: 798eb6c6-ac10-45de-a051-e3aec5e6dfd0
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 2b1715b1-8642-4b9c-8845-fc27c2ec7ca1
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: string
		lineageTag: 6960ec9b-ff45-4aa3-ad5d-5865dc2928cb
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

	column order_value
		dataType: int64
		formatString: 0
		lineageTag: ecbdedd3-288f-4db2-9b90-5cb4fa8a8c71
		summarizeBy: sum
		sourceColumn: order_value

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 0f2d75ec-7cc0-448f-bded-e49266349f5e
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\THAOVY\Downloads\SWE40006\orders.csv"),[Delimiter=",", Columns=5, Encoding=1258, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"customer_id", type text}, {"order_date", type text}, {"order_value", Int64.Type}, {"status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

